"""Shell completion engine.

Provides AI-powered, context-aware autocompletions for bash, zsh, and fish.
Completions are generated by sending shell context (current buffer, history,
working directory, environment) to the active AI provider and streaming
suggestions back via the daemon IPC socket.
"""

from blink.completions.broker import CompletionBroker
from blink.completions.context import CompletionContext
from blink.completions.ranker import Completion, HistoryRanker
from blink.completions.validator import Validator

__all__ = ["Completion", "CompletionBroker", "CompletionContext", "HistoryRanker", "Validator"]
