"""Shell completion engine.

Provides AI-powered, context-aware autocompletions for bash, zsh, and fish.
Completions are generated by sending shell context (current buffer, history,
working directory, environment) to the active AI provider and streaming
suggestions back via the daemon IPC socket.
"""
